version: '3.8'
services:
  backend:
    build: .
    container_name: activation-system
    restart: always
    ports:
      - "4000:4000"
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - .:/app
      - /app/node_modules
    command: sh -c "npm run build:wallet && npm start"

  studio:
    build: .
    container_name: activation-studio
    restart: always
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "127.0.0.1:5557:5555"
    command: sh -c "npx prisma studio --port 5555 --browser none"

  db:
    image: postgres:16
    container_name: activation-db
    restart: always
    environment:
      POSTGRES_USER: tguser
      POSTGRES_PASSWORD: tgpass123
      POSTGRES_DB: activation_system
    ports:
      - "7440:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
