version: '3.8'

services:
  app:
    build: ./app
    container_name: telegram_key_app
    restart: always
    env_file:
      - .env
    depends_on:
      - db_telegram
    volumes:
      - ./app:/app
    working_dir: /app
    command: ["python", "main.py"]  # временно, позже можно изменить

  db_telegram:
    image: postgres:15
    container_name: db_telegram
    restart: always
    environment:
      POSTGRES_DB: telegram_keys
      POSTGRES_USER: tguser
      POSTGRES_PASSWORD: tgpass123
    volumes:
      - telegram_pgdata:/var/lib/postgresql/data
    ports:
      - "5433:5432"

volumes:
  telegram_pgdata:
